### ISSUE TITLE
Add integration with codemetrics

### ISSUE THREAD

**Issue by jakagacic** [bornfight/README#22]
Add code metrics points for each filled .md file automatically

**Comment by tonymrakovcic** [comment]
I've made a zap that does this

It adds a new row to the new worksheet "GithubZap"

@krukru when you can, can you integrate it in the calculations, since I feel it will be a few minutes for you, and a lot more for me :)
I has a mergedAt that is empty if it's not merged

**Comment by tonymrakovcic** [comment]
Integrated with a Zap!
The zap adds a row to Form responses of codemetrics
